### ISSUE TITLE
error occurred when opening the node of Data.wz

### ISSUE THREAD

**Issue by zjb625** [lastbattle/Harepacker-resurrected#123]
maybe Canvas node? I don't really know

************** Exception Text **************
System.ObjectDisposedException: Cannot access a closed file.
   at System.IO.__Error.FileNotOpen()
   at System.IO.FileStream.get_Position()
   at MapleLib.WzLib.WzProperties.WzPngProperty.GetCompressedBytes(Boolean saveInMemory)
   at MapleLib.WzLib.WzProperties.WzPngProperty.GetRawImage(Boolean saveInMemory)
   at MapleLib.WzLib.WzProperties.WzPngProperty.ParsePng(Boolean saveInMemory, Texture2D texture2d)
   at MapleLib.WzLib.WzProperties.WzCanvasProperty.GetBitmap()
   at HaRepacker.GUI.Panels.MainPanel.ShowObjectValue(WzObject obj) in D:\Git\Harepacker-resurrected\HaRepacker\GUI\Panels\MainPanel.xaml.cs:line 1385
   at HaRepacker.GUI.Panels.MainPanel.DataTree_AfterSelect(Object sender, TreeViewEventArgs e) in D:\Git\Harepacker-resurrected\HaRepacker\GUI\Panels\MainPanel.xaml.cs:line 127
   at System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Download this Data.wz, it's from CMS 180
https://www.fengyewuyu.com/download/Data.wz

**Comment by zjb625** [comment]
looks has been fix but not release...sorry

**Comment by lastbattle** [comment]
Yes, it is not released yet. 
Feel free to compile it yourself in the meantime 😅
