### ISSUE TITLE
KMST 2023-06-10 - Fails to access .wz files

### ISSUE THREAD

**Issue by snowbie** [lastbattle/Harepacker-resurrected#209]
``
Error parsing Z:\Nexon\MapleT\Data\Sound\Sound.wz.wz (Error with game version hash : The specified game version is incorrect and WzLib was unable to determine the version itself).
``

```
************** Exception Text **************
System.Exception: Error parsing Z:\Nexon\MapleT\Data\Sound\Sound.wz.wz (Error with game version hash : The specified game version is incorrect and WzLib was unable to determine the version itself)
   at MapleLib.WzFileManager.LoadWzFile(String baseName, WzMapleVersion encVersion)
   at HaRepacker.GUI.MainForm.<>c__DisplayClass37_1.<openToolStripMenuItem_Click>b__1(String filePath) in E:\Server\Harepacker-resurrected\HaRepacker\GUI\MainForm.cs:line 972
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
````
Same error occurs with all of the .wz files. `[file].wz.wz`

**Comment by v3921358** [comment]
MapleStoryVerDetectedFromClient from MapleStroyT.exe seems to be 1155,

And It did not analyze at all because MAX_PATCH_VERSION was 1000

**Comment by v3921358** [comment]
Here's the latest KMST wz and exe
https://mega.nz/folder/6QgCTa7b#eJs07rzEdmtNE-wgtc9NOg
