### ISSUE TITLE
[HaCreator] Saving existing map under new map ID throws exception

### ISSUE THREAD

**Issue by voleth** [lastbattle/Harepacker-resurrected#251]
Opening up an existing map and then attempting to save it under a new map ID throws this exception:

> `************** Exception Text **************
> System.Exception: Could not find a suitable Map.wz to place the new map into.
>    at HaCreator.Wz.MapSaver.InsertImage() in E:\Server\Harepacker-resurrected\HaCreator\Wz\MapSaver.cs:line 78
>    at HaCreator.GUI.Save.saveButton_Click(Object sender, EventArgs e) in E:\Server\Harepacker-resurrected\HaCreator\GUI\Save.cs:line 136
>    at System.Windows.Forms.Control.OnClick(EventArgs e)
>    at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ButtonBase.WndProc(Message& m)
>    at System.Windows.Forms.Button.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> `

Though, doing New > Clone and then saving the new map ID does work. Which is the easier, faster, and smarter way to do it anyway.

**Comment by lastbattle** [comment]
Tested as of 2026-04-15, works.
