### ISSUE TITLE
Can't open files in latest release (GMS v256)

### ISSUE THREAD

**Issue by hyoretsu** [lastbattle/Harepacker-resurrected#276]
Getting all sorts of different errors. `.ini file at the directory 'MapleStory\Data\Packs' is missing, or unavailable.` when dragging file to HaRepacker, `Error with game version hash : The specified game version is incorrect and WzLib was unable to determine the version itself.` when opening 64-bit WZ file or folder (Skill) and `Nullable object must have a value.` when double-clicking a file to open with HaRepacker.

Game version error:
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Exception: Error parsing N:\SteamLibrary\steamapps\common\MapleStory\Data\Skill\Skill_000.wz.wz (Error with game version hash : The specified game version is incorrect and WzLib was unable to determine the version itself)
   at MapleLib.WzFileManager.LoadWzFile(String baseName, WzMapleVersion encVersion) in D:\Github\Harepacker-resurrected\MapleLib\MapleLib\WzFileManager.cs:line 327
   at HaRepacker.GUI.MainForm.<>c__DisplayClass36_1.<toolStripMenuItem_newWzFormat_Click>b__1(String filePath) in D:\Github\Harepacker-resurrected\HaRepacker\GUI\MainForm.cs:line 1015
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
HaRepackerResurrected
    Assembly Version: 1.0.0.0
    Location: 
----------------------------------------
System.Runtime
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Windows.Forms
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Collections.Specialized
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Threading.Thread
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Threading
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
MapleLib
    Assembly Version: 2.0.0.0
    Location: 
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.ObjectModel
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Location: 
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Linq
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Linq.Expressions
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Private.Uri
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Runtime.Numerics
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Runtime.Serialization.Primitives
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Data.Common
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Private.Xml
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.ComponentModel
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Collections
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Memory
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Location: 
----------------------------------------
System.Security.Principal.Windows
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Security.Claims
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.IO.Pipes
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Drawing.Common
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Location: 
----------------------------------------
PresentationCore
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Runtime.Loader
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Resources.Extensions
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Drawing
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
PresentationFramework
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
WindowsBase
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Xaml
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
DirectWriteForwarder
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Diagnostics.Debug
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Runtime.CompilerServices.VisualC
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
WindowsFormsIntegration
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Configuration.ConfigurationManager
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Net.WebClient
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.IO.Packaging
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
UIAutomationTypes
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Net.Primitives
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Windows.Extensions
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Windows.Controls.Ribbon
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
PresentationFramework.Aero2
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
Xceed.Wpf.Toolkit
    Assembly Version: 4.6.0.0
    Location: 
----------------------------------------
PresentationFramework-SystemXml
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.ComponentModel.Annotations
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Net.Requests
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Net.WebHeaderCollection
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
UIAutomationProvider
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
HaSharedLibrary
    Assembly Version: 1.0.0.0
    Location: 
----------------------------------------
ICSharpCode.AvalonEdit
    Assembly Version: 6.3.0.90
    Location: 
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
MonoGame.Framework
    Assembly Version: 3.8.2.1105
    Location: 
----------------------------------------
System.Security.AccessControl
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
PresentationFramework-SystemData
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Collections.Immutable
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.IO.MemoryMappedFiles
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Threading.Tasks.Parallel
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Security.Cryptography
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------

************** JIT Debugging **************
```

Nullable error:
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: Nullable object must have a value.
   at MapleLib.WzLib.Util.WzTool.DetectMapleVersion(String wzFilePath, Int16& fileVersion) in D:\Github\Harepacker-resurrected\MapleLib\MapleLib\WzLib\Util\WzTool.cs:line 191
   at HaRepacker.GUI.MainForm..ctor(String wzPathToLoad, Boolean usingPipes, Boolean firstrun) in D:\Github\Harepacker-resurrected\HaRepacker\GUI\MainForm.cs:line 128
   at HaRepacker.Program.Main(String[] args) in D:\Github\Harepacker-resurrected\HaRepacker\Program.cs:line 78


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
HaRepackerResurrected
    Assembly Version: 1.0.0.0
    Location: 
----------------------------------------
System.Runtime
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Windows.Forms
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Collections.Specialized
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Threading.Thread
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Threading
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
MapleLib
    Assembly Version: 2.0.0.0
    Location: 
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.ObjectModel
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Location: 
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Linq
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Linq.Expressions
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Private.Uri
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Runtime.Numerics
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Runtime.Serialization.Primitives
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Data.Common
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Private.Xml
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.ComponentModel
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Collections
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Memory
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Location: 
----------------------------------------
System.Security.Principal.Windows
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Security.Claims
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.IO.Pipes
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Drawing.Common
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Location: 
----------------------------------------
PresentationCore
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Runtime.Loader
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Resources.Extensions
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Drawing
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
PresentationFramework
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
WindowsBase
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Xaml
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
DirectWriteForwarder
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Diagnostics.Debug
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Runtime.CompilerServices.VisualC
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
WindowsFormsIntegration
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Configuration.ConfigurationManager
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Net.WebClient
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.IO.Packaging
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
UIAutomationTypes
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Net.Primitives
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Windows.Extensions
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Windows.Controls.Ribbon
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
PresentationFramework.Aero2
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
Xceed.Wpf.Toolkit
    Assembly Version: 4.6.0.0
    Location: 
----------------------------------------
PresentationFramework-SystemXml
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.ComponentModel.Annotations
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Net.Requests
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Net.WebHeaderCollection
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
UIAutomationProvider
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
HaSharedLibrary
    Assembly Version: 1.0.0.0
    Location: 
----------------------------------------
ICSharpCode.AvalonEdit
    Assembly Version: 6.3.0.90
    Location: 
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
MonoGame.Framework
    Assembly Version: 3.8.2.1105
    Location: 
----------------------------------------
System.Security.AccessControl
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Security.Cryptography
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Collections.Immutable
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.IO.MemoryMappedFiles
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------

************** JIT Debugging **************
```

.ini error:
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Exception: .ini file at the directory 'N:\SteamLibrary\steamapps\common\MapleStory\Data\Packs' is missing, or unavailable.
   at MapleLib.WzFileManager.BuildWzFileList() in D:\Github\Harepacker-resurrected\MapleLib\MapleLib\WzFileManager.cs:line 216
   at HaRepacker.GUI.MainForm.OpenFileInternal(String[] fileNames) in D:\Github\Harepacker-resurrected\HaRepacker\GUI\MainForm.cs:line 851
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
HaRepackerResurrected
    Assembly Version: 1.0.0.0
    Location: 
----------------------------------------
System.Runtime
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Windows.Forms
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Collections.Specialized
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Threading.Thread
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Threading
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
MapleLib
    Assembly Version: 2.0.0.0
    Location: 
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.ObjectModel
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Location: 
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Linq
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Linq.Expressions
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Private.Uri
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Runtime.Numerics
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Runtime.Serialization.Primitives
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Data.Common
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Private.Xml
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.ComponentModel
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Collections
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Memory
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Location: 
----------------------------------------
System.Security.Principal.Windows
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Security.Claims
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.IO.Pipes
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Drawing.Common
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Location: 
----------------------------------------
PresentationCore
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Runtime.Loader
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Resources.Extensions
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Drawing
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
PresentationFramework
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
WindowsBase
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Xaml
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
DirectWriteForwarder
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Diagnostics.Debug
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Runtime.CompilerServices.VisualC
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
WindowsFormsIntegration
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Configuration.ConfigurationManager
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Net.WebClient
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.IO.Packaging
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
UIAutomationTypes
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Net.Primitives
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Windows.Extensions
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Windows.Controls.Ribbon
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
PresentationFramework.Aero2
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
Xceed.Wpf.Toolkit
    Assembly Version: 4.6.0.0
    Location: 
----------------------------------------
PresentationFramework-SystemXml
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.ComponentModel.Annotations
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Net.Requests
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Net.WebHeaderCollection
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
UIAutomationProvider
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
HaSharedLibrary
    Assembly Version: 1.0.0.0
    Location: 
----------------------------------------
ICSharpCode.AvalonEdit
    Assembly Version: 6.3.0.90
    Location: 
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
MonoGame.Framework
    Assembly Version: 3.8.2.1105
    Location: 
----------------------------------------
System.Security.AccessControl
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
PresentationFramework-SystemData
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.Collections.Immutable
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------
System.IO.MemoryMappedFiles
    Assembly Version: 8.0.0.0
    Location: 
----------------------------------------

************** JIT Debugging **************
```

**Comment by HikariCalyx** [comment]
Known issue, see #243 . You may want to use WzComparerR2 updated since August 2024 to read those encrypted files.

**Comment by lastbattle** [comment]
Packs aren't supported, neither does the saving feature for versions with Canvas.wz in a separate file. Loading it works though, in both HaRepacker and HaCreator (staging branch).
Feel free to fork this project as you like, at the moment I simply do not have the bandwidth personally to do it.
