### ISSUE TITLE
2 important issues...

### ISSUE THREAD

**Issue by Arufonsu** [lastbattle/Harepacker-resurrected#50]
i have recently worked from a fork to make the .img loading possible in v83: https://github.com/Arufonsu/ClientImageLoader

welp, the following problems make harepacker pretty much useless for me rn u_u...
when i open a v83 .wz file with (old) gms encryption, lets say character.wz (201 MB) and attempt to save it somewhere else with my own encrypt keys, the result is a small (261 KB) unusable .wz file :/

There's also the 'System.Object[]' to type 'System.Int32[]' problem that doesn't allows you to extract a .wz's .img files.

tried compiling it by myself, even tried with the released compiled .exe, and the problem is always there, i even tried in a clean OS with the required runtime cores and .NET and still no luck.

it would be nice to be able to save .wz files with my own keys AND then being able to extract those .wz's encypted .img files (with my keys) in order to load them directly from .img files in the client.

**Comment by PirateIzzy** [comment]
I'm having a similar issue with editing in regards to #1 . I tested out editing Sound.wz, but when I try to Save it using the same encryption (BMS to load and BMS to save), the new Sound.wz file can't be loaded or worked with.

**Comment by lastbattle** [comment]
Would you mind uploading the WZ file that you're having issues with during extraction? 

'System.Object[]' to type 'System.Int32[]'

**Comment by Arufonsu** [comment]
> Would you mind uploading the WZ file that you're having issues with during extraction?
> 
> 'System.Object[]' to type 'System.Int32[]'

any clean v83 .wz

try with any of these:
https://drive.google.com/drive/folders/1cdmhGlCW36DlEvbtsrkIttm5qf73zWs5

**Comment by lastbattle** [comment]
I've just tested Mob.wz, Character.wz, and Map.wz with the latest build of harepacker (under staging branch)
It extracts fine without issues with 'System.Object[]' to type 'System.Int32[]'.

**Comment by PirateIzzy** [comment]
So I replaced one of the sound files in Sound.wz -> Mob.img and was able to save it fine. Now I face a different issue, where attempting to open any of the .img files results in this error:
![image](https://user-images.githubusercontent.com/34289651/85086569-f9b17480-b1a8-11ea-981f-2d0e9ad08707.png)

The full stack trace is as follows:

````See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.
************** Exception Text **************
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.BinaryReader.ReadByte()
   at MapleLib.WzLib.WzImage.ParseImage(Boolean forceReadFromData)
   at HaRepacker.GUI.Panels.MainPanel.ParseOnDataTreeSelectedItem(WzNode selectedNode, Boolean expandDataTree) in C:\Izzy\HaRepacker 3.5\New folder\Harepacker-resurrected\HaRepacker\GUI\Panels\MainPanel.xaml.cs:line 133
   at HaRepacker.GUI.Panels.MainPanel.DataTree_DoubleClick(Object sender, EventArgs e) in C:\Izzy\HaRepacker 3.5\New folder\Harepacker-resurrected\HaRepacker\GUI\Panels\MainPanel.xaml.cs:line 110
   at System.Windows.Forms.Control.OnDoubleClick(EventArgs e)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
HaRepackerResurrected
    Assembly Version: 4.2.4.0
    Win32 Version: 4.2.4.0
    CodeBase: file:///C:/Izzy/HaRepacker%203.5/New%20folder/Harepacker-resurrected/Compiled/Release/AnyCPU/HaRepackerResurrected.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4150.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
MapleLib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///C:/Izzy/HaRepacker%203.5/New%20folder/Harepacker-resurrected/Compiled/Release/AnyCPU/MapleLib.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.3.23909
    CodeBase: file:///C:/Izzy/HaRepacker%203.5/New%20folder/Harepacker-resurrected/Compiled/Release/AnyCPU/Newtonsoft.Json.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
WindowsFormsIntegration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4150.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/WindowsFormsIntegration/v4.0_4.0.0.0__31bf3856ad364e35/WindowsFormsIntegration.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
HaSharedLibrary
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Izzy/HaRepacker%203.5/New%20folder/Harepacker-resurrected/Compiled/Release/AnyCPU/HaSharedLibrary.DLL
----------------------------------------
PresentationFramework.Aero2
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero2/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero2.dll
----------------------------------------
WpfAnimatedGif
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///C:/Izzy/HaRepacker%203.5/New%20folder/Harepacker-resurrected/Compiled/Release/AnyCPU/WpfAnimatedGif.DLL
----------------------------------------
PresentationFramework-SystemXml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXml/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXml.dll
----------------------------------------
PresentationFramework-SystemData
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemData/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemData.dll
----------------------------------------
UIAutomationTypes
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
----------------------------------------
UIAutomationProvider
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationProvider/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationProvider.dll
----------------------------------------
************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.
For example:
<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>
When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.````

**Comment by Arufonsu** [comment]
> Maybe you can point me into the right direction if you are still having issues with the latest build.
uhm? is there a commit related with this issue since i posted this issue? if so i will then give a try to the latest version... also i think i pretty much explained every possible scenario to reproduce this problem, i tested this in 2 different PCs with the latest version of W10 OS, installed the basic dependencies like VS runtimes and there's obviosuly the latest 4.8 Net frame installed by default as the last version of w10 OS.. if there's any other depency i should be aware of or setting change that needs to be done in order to run this build properly, it would be nice to know it!
