### ISSUE TITLE
Harepacker unable to open latest MSEA Skill001.wz and Skill.wz consistently, maxes out ram usage

### ISSUE THREAD

**Issue by tomyummmm** [lastbattle/Harepacker-resurrected#61]
*Update* 

> Look at Edit 3 below for quick fix, but this prevents backwards compatibility with older versions of maple *.wz files. The ram usage and long processing time seems to be due to WzFile.cs Line 222, the checking of every version and hash is inefficient and might be the cause of memory runaway issue i was facing.

Hello, the latest patch of v196 in MSEA cause harepacker to be unable to open either skill or skill001.wz, if it does not hang or crash outright. It will loop the loading screen, but task manager shows the program increasing ram usage until it maxes out ram, which then switches over to writing and reading from the disk. 

It is repeatable everytime i open skill001.wz everytime, and only successfully loads maybe once every 10 tries. Only version of harepacker which can open it successfully without maxing out ram is the original harepacker that this project is forked from.

![image](https://user-images.githubusercontent.com/65211592/86317904-2bbfdd80-bc63-11ea-8e0c-89af99575948.png)

Edit: I have downloaded the latest version of the required submodules and programs required to build and test your master. Still facing the same issues. Also, changing to black theme causes the program to not open and throw exceptions. 

```
************** Exception Text **************
System.InvalidOperationException: 'button_animateSelectedCanvas' name cannot be found in the name scope of 'System.Windows.Controls.DockPanel'.
   at System.Windows.Media.Animation.Storyboard.ResolveTargetName(String targetName, INameScope nameScope, DependencyObject element)
   at System.Windows.Media.Animation.Storyboard.ClockTreeWalkRecursive(Clock currentClock, DependencyObject containingObject, INameScope nameScope, DependencyObject parentObject, String parentObjectName, PropertyPath parentPropertyPath, HandoffBehavior handoffBehavior, HybridDictionary clockMappings, Int64 layer)
   at System.Windows.Media.Animation.Storyboard.ClockTreeWalkRecursive(Clock currentClock, DependencyObject containingObject, INameScope nameScope, DependencyObject parentObject, String parentObjectName, PropertyPath parentPropertyPath, HandoffBehavior handoffBehavior, HybridDictionary clockMappings, Int64 layer)
   at System.Windows.Media.Animation.Storyboard.BeginCommon(DependencyObject containingObject, INameScope nameScope, HandoffBehavior handoffBehavior, Boolean isControllable, Int64 layer)
   at System.Windows.VisualStateGroup.StartNewThenStopOld(FrameworkElement element, Storyboard[] newStoryboards)
   at System.Windows.VisualStateManager.GoToStateInternal(FrameworkElement control, FrameworkElement stateGroupsRoot, VisualStateGroup group, VisualState state, Boolean useTransitions)
   at System.Windows.VisualStateManager.GoToStateCommon(FrameworkElement control, FrameworkElement stateGroupsRoot, String stateName, Boolean useTransitions)
   at HaRepacker.GUI.Panels.MainPanel..ctor() in C:\Users\mervi\Documents\GitHub\Harepacker-resurrected\HaRepacker\GUI\Panels\MainPanel.xaml.cs:line 60
   at HaRepacker.GUI.MainForm.AddTabsInternal(String defaultName) in C:\Users\mervi\Documents\GitHub\Harepacker-resurrected\HaRepacker\GUI\MainForm.cs:line 522
   at HaRepacker.GUI.MainForm..ctor(String wzToLoad, Boolean usingPipes, Boolean firstrun) in C:\Users\mervi\Documents\GitHub\Harepacker-resurrected\HaRepacker\GUI\MainForm.cs:line 46
   at HaRepacker.Program.Main(String[] args) in C:\Users\mervi\Documents\GitHub\Harepacker-resurrected\HaRepacker\Program.cs:line 73
```

Edit 2: Google drive link added for Skill001.wz
https://drive.google.com/file/d/1B6ty6lwwO_mgXTDoy0frycGkaFTUzkpF/view?usp=sharing

Edit 3: Wzfile.cs line 222, i changed int j = 190 so it doesnt check so many times.

```
for (int j = 190; j < MAX_PATCH_VERSION; j++)
                {
                    this.mapleStoryPatchVersion = (short)j;
                    this.versionHash = GetVersionHash(version, mapleStoryPatchVersion);
                    if (this.versionHash == 0)
                    {
                        continue;
                    }
                    reader.Hash = this.versionHash;
                    long position = reader.BaseStream.Position; // save position to rollback to, if should parsing fail from here
                    WzDirectory testDirectory;
```

**Comment by lastbattle** [comment]
Fixed one of them, it happens from time to time as the version number isn't known by harepacker. Nexon stores them in MapleStory.exe.
It's more or less a guesstimate via bruteforce when opening..

https://github.com/lastbattle/Harepacker-resurrected/commit/c3491d520a223ba75892fa62ae61fb6c9e4b0af0

**Comment by lastbattle** [comment]
annddd 
https://github.com/lastbattle/Harepacker-resurrected/commit/fbaa9d13c115b2a9217d00033d039ce9c02b0ac0

**Comment by tomyummmm** [comment]
Staging branch tested and working, thanks.
