### ISSUE TITLE
export animations?

### ISSUE THREAD

**Issue by seth1** [lastbattle/Harepacker-resurrected#78]
Presently you can view animations by more>animate, but is there any way to export them as a single animated image?

**Comment by lastbattle** [comment]
You'll be able to export it when you click on the sub directory, but not with 100% certainty. I have been trying to fix that lately.

![Untitled](https://user-images.githubusercontent.com/4586194/98390205-023f1480-2090-11eb-9334-a51d6033f24c.png)

**Comment by Piezoelectric** [comment]
Hello! Not sure if you're still working on animation exports. I ran into this error when trying to export an animation; maybe this might help you with debugging.

When I navigate to `Skill.wz > 10000 > 10001283 > effect0`  and I try clicking "Save image animation", I get the following:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.OverflowException: Arithmetic operation resulted in an overflow.
   at HaSharedLibrary.SharpApng.SharpApngBasicWrapper.MarshalString(String source) in D:\Git\Harepacker-resurrected\HaSharedLibrary\SharpApng\SharpApngBasicWrapper.cs:line 42
   at HaSharedLibrary.SharpApng.SharpApngBasicWrapper.SaveApngManaged(String path, Int32 frameCount, Int32 width, Int32 height, Boolean firstFrameHidden) in D:\Git\Harepacker-resurrected\HaSharedLibrary\SharpApng\SharpApngBasicWrapper.cs:line 92
   at HaSharedLibrary.SharpApng.SharpApng.WriteApng(String path, Boolean firstFrameHidden, Boolean disposeAfter) in D:\Git\Harepacker-resurrected\HaSharedLibrary\SharpApng\SharpApng.cs:line 82
   at HaRepacker.AnimationBuilder.ExtractAnimation(WzSubProperty parent, String savePath, Boolean apngFirstFrame) in D:\Git\Harepacker-resurrected\HaRepacker\AnimationBuilder.cs:line 142
   at HaRepacker.GUI.Panels.MainPanel.MenuItem_saveImageAnimation_Click(Object sender, RoutedEventArgs e) in D:\Git\Harepacker-resurrected\HaRepacker\GUI\Panels\MainPanel.xaml.cs:line 887
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at HaRepacker.Program.Main(String[] args) in D:\Git\Harepacker-resurrected\HaRepacker\Program.cs:line 70
```
